Dev3
aldav99/exercise1 pull request #3
Opened 2018-09-30 10:27 UTC by aldav99

2018-09-30 12:00 UTC, vkurennov requested changes

2018-09-30 12:00 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def show
У нас список ответов, а также форма ответа должны быть на странице вопроса. Поэтому для ответов не имеют смысла экшены (и виды) index, show и new

2018-09-30 12:00 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.user_id = current_user.id
Не надо связывать по id, работай с объектами: `@answer.user = current_user` в этом и есть смысл ассоциаций и ORM - абстрагироваться от базы данных и работать с объетами.
А вот сравнивать как раз лучше по id, чтобы не делать лишний запрос.

2018-09-30 12:00 UTC, vkurennov commented on app/controllers/answers_controller.rb
>        render :new
new больше не нужен, форма на странице вопроса, вот ее и надо рендерить

2018-09-30 12:00 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      current_user == @answer.user
1. Вот тут как раз стоит сравнивать по user_id, чтобы не тянуть ассоциацию (читай - делать лишний запрос к базе), ведь user нам нужен только для сравнения, больше мы его никак не используем
2. Такая проверка нужна будет не раз, поэтому стоит ее вынести в метод `User#auhtor_of?`, чтобы не дублировать код

2018-09-30 12:00 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def author?
Дублирование. Замени на вызов `User#author_of?`

2018-09-30 12:00 UTC, vkurennov commented on app/views/answers/index.html.slim
> +p= 'Question:  ' + @question.body
1. Используй интерполяцию, а не конкатенацию в руби для склеивания строк. 
2. index для ответов не нужен, список ответов должен быть на странице вопроса

2018-09-30 12:00 UTC, vkurennov commented on app/views/answers/index.html.slim
> +        td= link_to 'Delete answer', answer, :method => :delete, :data => {:confirm => 'Are you sure?'}
Зачем показывать ссылку на удаление всем? Показывай только автору

2018-09-30 12:00 UTC, vkurennov commented on app/views/questions/index.html.slim
> +        td = question.body
Стоит вывести заголовок вопроса, а при клике на него уже показывать тело, список ответов и форму нового ответа

2018-09-30 12:00 UTC, vkurennov commented on app/views/questions/index.html.slim
> +        td = link_to 'Show answer',  question_answers_path(question)
Нет, должна быть одна страница, где будет сам вопрос и список его ответов, это страница вопроса

2018-09-30 12:00 UTC, vkurennov commented on app/views/questions/index.html.slim
> +        td= link_to 'Delete question', question, :method => :delete, :data => {:confirm => 'Are you sure?'}
Показывай эту ссылку только автору.

2018-09-30 12:00 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = f.label :correct
Зачем вообще это поле? Как человек, дающий ответ на вопрос другого человека, может знать правильный это ответ или нет? Наверное, это автор **вопроса** должен решать (и у нас дальше будет такая задача). А пока смысла в этом поле нет никакого. Не проектируй "на будущее", делай то, что требуется, но не более.

2018-09-30 12:00 UTC, vkurennov commented on config/routes.rb
>    resources :questions, shallow: true do
Если у корневого ресурса стоит shallow, то у вложенных можно не указывать, это происходит автоматом.

2018-09-30 12:00 UTC, vkurennov commented on spec/acceptance/author_can_delete_answer_spec.rb
> +    expect(page).to have_content 'The answer is deleted!!!'
До удаления надо проверить, что ответ есть на странице, после - что его нет. Проверка  флеш-сообщения не доказывает, что ответ реально был удален

2018-09-30 12:00 UTC, vkurennov commented on spec/acceptance/author_can_delete_answer_spec.rb
> +    click_on 'Delete answer'
Лучше проверять, что в принципе не видна такая ссылка на странице

2018-09-30 12:00 UTC, vkurennov commented on spec/acceptance/author_can_delete_answer_spec.rb
> +  scenario 'Another user cannot delete answer' do
Нужен похожий сценарий для незалогиненного юзера

2018-09-30 12:00 UTC, vkurennov commented on spec/acceptance/author_can_delete_question_spec.rb
> +    expect(page).to have_content 'The question is deleted!!!'
Тут тоже этой проверки не достаточно. Нужно проверить, что сначала вопрос есть, а после удаления его нет на странице

2018-09-30 12:00 UTC, vkurennov commented on spec/acceptance/author_can_delete_question_spec.rb
> +  scenario 'Another user cannot delete question' do
Нужен похожий сценарий для незалогиненного юзера

2018-09-30 12:00 UTC, vkurennov commented on spec/acceptance/author_can_delete_question_spec.rb
> +    click_on 'Delete question'
Лучше проверять, что ссылка не видна

2018-09-30 12:00 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +    expect(page).to have_content 'Your question successfully created.'
Нужно проверит наличие заголовка и тела вопроса на странице после создания

2018-09-30 12:00 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +feature 'Create question', %q{
Нужен сценарий на ошибки валидации - проверить, что система выводит их пользователю.

2018-09-30 12:00 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +  scenario 'Authenticated user view the questions list' do
Это другая фича, она относится к просмтору списка вопросов и не имеет отношения к созданию вопроса. Каждая фича должна быть в своем файле

2018-09-30 12:00 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +  scenario 'Authenticated user create the answer' do
Создание ответа - это тоже отдельная фича, нужно вынести ее в отдельный файл, и она содержит несколько сценариев (те же, что и первые  для создания вопроса + на невалидный ответ)

2018-09-30 12:00 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +    expect(page).to have_content 'Your answer successfully created.'
Нужно проверить, что ответ есть на странице

2018-09-30 12:00 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +    expect(page).to have_content 'Your question and answers'
Эта проверка доказывает только наличие заголовка на странице, но никак не доказывает, что там выволдится еще и вопрос с ответами.

2018-09-30 12:00 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +  scenario 'Authenticated user is able to view questions and answers' do
Этот сценарий относится к фиче просмотра вопроса, а не создания.

2018-09-30 12:00 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +    click_on 'Ask question'
При тесте просмотра вопроса и ответов, они должны быть созданы заранее через фабрики. Причем, ответы должны быть разные (используй sequence) и их должно быть несколько, чтобы проверить, что действительно выводится список. Это же относится и к сценарию просмотра списка вопросов.

2018-09-30 12:00 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { user_id: @current_user, question_id: @question, answer: attributes_for(:answer) } }.to change(@question.answers, :count).by(1)
user_id не передается в парамтрах, мы его берем напрямую в экшене через метод current_user.

2018-09-30 12:00 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>        it 'saves the new answer in the database' do
Нужно также проверить и связь с юзером

2018-09-30 12:00 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { user_id: @current_user, question_id: @question, answer: attributes_for(:answer) } }.to change(@question.answers, :count).by(1)
Откуда взялась переменная @current_user, что в ней находится?

2018-09-30 12:00 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      allow_any_instance_of(AnswersController).to receive(:current_user) { user }
Чтобы не приходилось делать так (тут естьт подводные камни), мы как раз и написали хелпер `sign_in_user`

2018-09-30 12:00 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      allow_any_instance_of(AnswersController).to receive(:current_user) { @user }
Используй хелпер sign_in_user

2018-09-30 12:00 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    before { @user.answers << @answer }
1. зачем 2 before? Сделай один и в нем напиши несколько строк, как ты это делаешь в 125-127 строках
2. Используй фабрики и ассоциации в низ, чтобы не приходилось такой вот код писать. Почитай [документацию к фабрикам](https://www.rubydoc.info/gems/factory_bot/file/GETTING_STARTED.md)

2018-09-30 12:00 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>    describe 'DELETE #destroy' do
У тебя в destroy есть условие - надо проверять все возможные варианты

2018-09-30 12:00 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid attributes' do
нужно проверить связь с залогиненным юзером

2018-09-30 12:00 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
У тебя условие в destroy - надо проверять все варианты

2018-09-30 12:00 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    before { @user.questions << question }
См. замечания к тестам `AnswersController#destroy`

2018-10-02 08:26 UTC, aldav99 commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid attributes' do
Можно пояснить. Ведь из метода  sign_in_user вызывается sign_in, в котором нажимается Log in?
Спасибо

2018-10-05 11:14 UTC, vkurennov requested changes

2018-10-05 11:14 UTC, vkurennov commented on app/controllers/answers_controller.rb
> -    @answers = @question.answers
Ну так раз экшены не нужны, то надо не только тело у них удалить, но и сами методы. Зачем они тут пустые? А также виды соответсвующие тоже удалить

2018-10-05 11:14 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @question
Нельзя редиректить при невалидном объекте, так ты теряешь и информацию об ошибках валидации и то, что ввел пользователь. И вместо того, чтобы дать возможность исправить ошибку, заставляешь пользователя заново все набирать.
Тут нужен рендер той страницы, на которой была форма.

2018-10-05 11:14 UTC, vkurennov commented on app/models/question.rb
> +
В начале класса пустая строка не ставится

2018-10-05 11:14 UTC, vkurennov commented on app/models/user.rb
> +      self.id == obj.user_id if obj.respond_to?(:user_id)
Что-то многовато пробелов в начале. Должно быть 2.

2018-10-05 11:14 UTC, vkurennov commented on app/views/questions/index.html.slim
> +  p= link_to 'Log out', destroy_user_session_path, method: :delete
Вот это должно быть на кадой странице, поэтому стоит вынести в лейаут.

2018-10-05 11:14 UTC, vkurennov commented on app/views/questions/index.html.slim
> +        td = link_to "#{question.title}", question_path(question)
В первом параметра совсем не нужна интерполяция. `question.title `и так вернет строку

2018-10-05 11:14 UTC, vkurennov commented on app/views/questions/index.html.slim
> +        - if (current_user && current_user.author_of?(question))
Скобки здесь не нужны. А если применить [safe navigation operator](http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/), то все еще короче станет:

`if current_user&.author_of(question)`

2018-10-05 11:14 UTC, vkurennov commented on app/views/questions/index.html.slim
> +          td= link_to 'Delete question', question, :method => :delete, :data => {:confirm => 'Are you sure?'}
Используй **всегда**  новый вид записи хеша - через двоеточие: `method: :delete` и т.д.

2018-10-05 11:14 UTC, vkurennov commented on app/views/questions/new.html.slim
> += form_for @question do |f|
Вынеси это в универсальный паршл для ошибок и используй в разных формах

2018-10-05 11:14 UTC, vkurennov commented on app/views/questions/show.html.slim
> +        - if (current_user && current_user.author_of?(answer))
Используй safe navigation, как в комментарии выше я показал

2018-10-05 11:14 UTC, vkurennov commented on app/views/questions/show.html.slim
> +          td= link_to 'Delete answer', answer, :method => :delete, :data => {:confirm => 'Are you sure?'}
Используй новый стиль записи хешей

2018-10-05 11:14 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = form_for [@question, @question.answers.build] do |f|
А где вывод ошибок валидации?

2018-10-05 11:14 UTC, vkurennov commented on spec/acceptance/author_can_delete_answer_spec.rb
> +    expect(page).to have_content 'Delete answer'
Проверять надо не наличие ссылки, а тело ответа на странице. А после удаления - отсутсвие тела ответа. а то вдруг у тебя только ссылка исчезает, а ответ не удаляется. Это был бы баг, а тест бы его пропустил.

2018-10-05 11:14 UTC, vkurennov commented on spec/acceptance/author_can_delete_answer_spec.rb
> +    sign_in(user)
Все можно сделать проще: через фабрики создать вопрос, ответ, а затем зайти под другим юзером и проверить, что нет ссылки на удаление. Вообще, все подготовительные данные надо создавать через фабрики, через интерфейс создаем только то, что влияет на выполнение теста. Здесь же создание вопроса и ответа никак на сам тест не влияет (т.е. не важно, как именно они были созданы, важно, что они есть на начало работы теста).

2018-10-05 11:14 UTC, vkurennov commented on spec/acceptance/author_can_delete_answer_spec.rb
> +    expect(page).to have_no_content 'Delete answer'
Лучше `have_no_link`

2018-10-05 11:14 UTC, vkurennov commented on spec/acceptance/author_can_delete_answer_spec.rb
> +  scenario 'Unloged user cannot delete answer' do
См. комментарий выше насчет создания начальных данных. Тут ты еще и код дублируешь.

2018-10-05 11:14 UTC, vkurennov commented on spec/acceptance/author_can_delete_answer_spec.rb
> +    expect(page).to have_no_content 'Delete answer'
Лучше `have_no_link`

2018-10-05 11:14 UTC, vkurennov commented on spec/acceptance/author_can_delete_question_spec.rb
> +    expect(page).to have_no_content 'Test question'
Вот здесь все верно. Почему в тесте на удаление ответа ты делаешь по-другому?

2018-10-05 11:14 UTC, vkurennov commented on spec/acceptance/author_can_delete_question_spec.rb
> +    create_question
Создавай данные через фабрики до теста (используй `given!` для этого)

2018-10-05 11:14 UTC, vkurennov commented on spec/acceptance/author_can_delete_question_spec.rb
> +    create_question
Создавай данные до теста

2018-10-05 11:14 UTC, vkurennov commented on spec/acceptance/create_answer_spec.rb
> +    expect(page).to have_content "NOT"
Этого недостаточно. Мало ли что за "NOT" есть на странице. Надо проверить хотя бы одно полное сообщение об ошибке валидации (те сообщения, которые от валидаций в модели, а не то, что ты в контроллере через флеш-сообщения показываешь)

2018-10-05 11:14 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +    click_on 'Back'
А зачем назад возвращаться? Логично на странице вопроса показать и заголовок и тело. Посмотри на stackoverflow.com, как там сделано? Это можно брать за образец.

2018-10-05 11:14 UTC, vkurennov commented on spec/acceptance/view_answers_list_spec.rb
> +  before {@question = create(:question_with_answers)}
Замени на `given!(:question) { create(:question_with_answers) }` и в тестах обращайся к `question`

2018-10-05 11:14 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { question_id: @question, answer: attributes_for(:answer) } }.to change(@user.answers, :count).by(1)
В тестах моделей и контроллеров принято правило "один тест - один expect",  это только в acceptance-тестах можно несколько expect'ов  писать в одном тесте. Раздели на 2 отдельных теста.

2018-10-05 11:14 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    sign_in_user
Раздели тесты на 2 контекста - будет читаться гораздо лучше. Один контекст для автора, другой - для не автора. Кроме того, в случае не автора, нужно также проверить куда был редирект

2018-10-05 11:14 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      expect { delete :destroy, params: { id: @author_answer }}.to change(@author.answers, :count).by(0)
Ты же не пишешь "кол-во изменилось на 0", ты пишешь "кол-во не изменилось". Вот и тут также напиши (`to_not change...`)

2018-10-05 11:14 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid attributes' do
Не совсем, это другой метод sign_in_user, который в тестах контроллера используется. Там не нажимаются кнопки. Но не это важно.
Суть в том, что факт того, что ты залогинил пользователя перед тестом, никак не доказывает того, что именно с этим пользователем ты и связал вопрос в контроллере. Вдруг в контроллере ты все ответы связываешь с User.first или вообще в модели сделал ассоциацию с юзером необязательной и связь не устанавливаешь. Вот чтобы этого избежать, мы и должны проверить, что связь устанавливается.

Цель тестов - доказать, что код работает верно и делает то, что нужно.

2018-10-05 11:14 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
Теперь здесь нужны 2 контекста - для автора и для не-автора и в последнем еще и тест  на редирект

2018-10-05 11:14 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User do
Где тесты на метод `author_of?` Любой код, который ты пишешь в моделях/контроллерах должен покрываться соответсвующим тестами. А в идеале, перед тем, как писать код, ты должен спросить "есть ли у меня на него тесты?" и если нет, то начать с них.

2018-10-06 04:07 UTC, aldav99 commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
Можно ли пояснить: ведь у не-автора в принципе нет кнопки DELETE, как ситуация удаления вопроса может вообще возникнуть?

2018-10-08 10:01 UTC, vkurennov requested changes

2018-10-08 10:01 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      render 'questions/show', {answer: @answer}
Не нужно передавать answer как параметр. У тебя есть @answer, установленный в этом экшене, ты его в виде и должен использовать.

2018-10-08 10:01 UTC, vkurennov commented on app/views/questions/index.html.slim
> +- if user_signed_in?
Вынеси ссылки на логин/логаут в лейаут, чтобы на любой странице можно было залогиниться и выйти.

2018-10-08 10:01 UTC, vkurennov commented on app/views/questions/show.html.slim
> +- unless @answer
Вот это не лучшая проверка. Понятно для чего она сделана, но она не защитит от невалидного ответа. Лучше внутри цикла добавить проверку ответов на `persisted?`, так ты будешь выводить только сохраненные в базе ответы.

2018-10-08 10:01 UTC, vkurennov commented on spec/acceptance/author_can_delete_answer_spec.rb
> +    @author = create(:user)
Все эти данные из before запиши через `given`. Если они нужны до теста, что через `given!`. В before должны быть только начальные действия, все данные готовим через given/given!
В этом и отличие: код, заданный через `given` выполняется в момент первого вызова, а заданный через `given!` выполняется автоматически, перед каждым тестом.

2018-10-08 10:01 UTC, vkurennov commented on spec/acceptance/author_can_delete_question_spec.rb
> +  before { create(:question, user: user, title: 'Test question') }
Замени здесь before на `given!` и все будет правильно. Логика такая: в let/given ты определяешь начальные данные, которые нужны в тестах и можешь в тестах же к ним обращаться. В before ты задаешь начальные действия, которые должны предшествовать тестам.

2018-10-08 10:01 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      @author = create(:user_with_answers)
Вынеси в `let`

2018-10-08 10:01 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
Очень просто: злоумышленник делает прямой HTTP-запрос на удаление **любого** ответа, просто зная его id. Сделать запрос в обход интерфейса проще простого, существует милллион утилит для этого.

Надо понимать, что вид - это вообще не про защиту, это про удобство использования и интерфейс в целом, а защита должна работать уже на сервере, только там можно как-то защититься от неправомерных запросов.

2018-10-08 10:01 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +      @author = create(:user_with_questions)
Вынеси в `let`

2018-10-08 10:01 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { delete :destroy, params: { id: @author_question }}.to change(@author.questions, :count).by(0)
`to_not change`, а не `change(...).by(0)`

2018-10-08 10:01 UTC, vkurennov commented on spec/models/user_spec.rb
> +      expect(user.author_of?(question)).to be_truthy
Есть более красивый синтаксис, работает для любых методов-предикатов:

`expect(user).to be_author_of(question)`

то есть, вызов метода переносим вправо, после to/to_not, добавляем be_ и убираем вопр. знак.

2018-10-08 10:01 UTC, vkurennov commented on spec/models/user_spec.rb
> +      expect(user.author_of?(answer)).to be_truthy
У тебя универсальный метод, он не зависит от типа аргумента, а только от наличия у него user_id, поэтому проверять на вопросе и ответе не нужно. Нужно проверить на одном любом из них. А вот проверить, что будет, если передать объект без user_id в метод, стоит.

2018-10-09 07:51 UTC, vkurennov approved these changes

2018-10-09 07:51 UTC, vkurennov commented on spec/acceptance/author_can_delete_question_spec.rb
> +    another_user = create(:user)
Тоже стоило вынести в  given

2018-10-10 01:01 UTC, merged