Dev5
aldav99/exercise1 pull request #5
Opened 2018-10-26 04:06 UTC by aldav99

2018-10-26 09:09 UTC, vkurennov requested changes

2018-10-26 09:09 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to @answer.question
Т.к. мы переделываем на ajax все, то обычную, html-версию можно не поддерживать, оставив только js-формат

2018-10-26 09:09 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      Answer.flip_best(@answer)
А почему бы не сделать это инстанс-методом? Ты ведь производишь операцию над конкретным объектом, вот и вызывай у него метод: `@answer.flip_best` (хотя лучше `toggle_best`).
Всегда, когда ты делаешь метод класса, в который передаешь объект этого же класса, это ошибка и она означает, что здесь нужен инстанс-метод. Методы класса используются только когда нет конкретного объекта, над которым производится действие.

2018-10-26 09:09 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    redirect_to @answer.question
Это тоже ajax-действие должно быть, тут не должно быть никаких редиректов. Должен быть js-ответ, который отрендерит список ответов и обновит его на странице без редиректа. Весь смысл ajax в том, чтобы не делать редиректов. Да, рельсы в последних версиях умеют делать редирект в ajax-запросах и это выгляди так, как будто страница не перегружается, но на самом деле, все равно просиходит полная загрузка страницы, пусть и в фоне, а именно этого и нужно избежать.

2018-10-26 09:09 UTC, vkurennov commented on app/models/answer.rb
> +    former_best = Answer.former_best.first
у тебя что, один вопрос в системе? Почему ты глобально ищешь лучший ответ, без привязки к вопросу? Что, если у вопроса 1 уже есть лучший ответ, а мы назначаем лучший ответ вопросу 2? В твоем случае, у вопроса 1 лучший ответ пропадет.

2018-10-26 09:09 UTC, vkurennov commented on app/models/answer.rb
> +      former_best.best = false
Используй метод `update!` для обновления атрибута в одну строку.

2018-10-26 09:09 UTC, vkurennov commented on app/models/answer.rb
> +    answer.best = true
И тут тоже нужен метод `update`

2018-10-26 09:09 UTC, vkurennov commented on app/controllers/questions_controller.rb
>    def update
Здесь тоже нужно избавиться от редиректа и обновлять только нужную часть страницы через js-ответ

2018-10-26 09:09 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +    p= link_to 'Delete answer', answer, method: :delete, id: answer.id, :data => {confirm: 'Are you sure?', remote: true}
1. По стандарту, html-атрибут id не может начинаться с цифры, только с буквы, это может вести к некорректной работе скриптов в некоторых браузерах.
2. Используй всегда новый стиль хешей, через двоеточие (атрибут `data`)

2018-10-26 09:09 UTC, vkurennov commented on app/views/answers/destroy.js.erb
> +var element = document.getElementById("<%=j @answer.id %>");
Ты в курсе, что удаляешь не сам ответ, а только ссылку на его удаление? потому что id с таким значением у тебя прописан именно для ссылки.

2018-10-26 09:09 UTC, vkurennov commented on app/views/answers/update.js.erb
> +  $('.answers').html('<%= j render @question.answers %>');
Нужно не рендерить весь список, а обновлять только нужный ответ.

2018-10-26 09:09 UTC, vkurennov commented on app/views/questions/edit.html.slim
> +h1= "Update question"
По заданию, редактирование вопроса нужно переделать на ajax, чтобы форма редактирования была на странице вопроса и появлялась по клику, т.е. аналогично редактированию ответов.

2018-10-26 09:09 UTC, vkurennov commented on app/views/questions/edit.html.slim
> +  = f.text_field :title, placeholder: @question.title
Зачем это делать через placeholder? Если просто оставить `f.text_field :title`, то в поле и так будет подставлен текст из соответствующего поля

2018-10-26 09:09 UTC, vkurennov commented on app/views/questions/show.html.slim
>    = render @answer
Это что за особый ответ, который ты рендеришь отдельно? почему он не входит в общий список ответов, который рендерится строкой выше?

2018-10-26 09:09 UTC, vkurennov commented on spec/acceptance/author_can_opt_best_answer_spec.rb
> +    expect(page).to have_css("p#true", count: 1)
Бессмысленная проверка, она не меняется что до действия, что после. А значит, мы вообще не можем отследить были ли изменения. Нужно изменить проверку. Кроме того, сама проверка не информативна совершенно, что это за тег p с id true? Может, он статически прописан в коде страницы

2018-10-26 09:09 UTC, vkurennov commented on spec/acceptance/author_can_opt_best_answer_spec.rb
> +    expect(page).to have_css(".answers p:first-child#true")
Этого недостаточно. Ты лишь проверил, что такой элемент есть на странице, но это не значит, что он содержит тело ответа. Надо проверить, что внутри этого элемента нужный текст.

Далее, в этом тесте нельзя просто напрямую создать лучший ответ, так тест теряет смысл, потому что не тестирует поведение разрабатываемой функции. Нужно проверить, что в результате клика по ссылке "Best answer?" первым ответом стал именно тот, у которого был клик по ссылке. Можно объеденить этот тест с самым первым

2018-10-26 09:09 UTC, vkurennov commented on spec/acceptance/author_can_opt_best_answer_spec.rb
> +feature 'Author can opt best answer', %q{
Допиши тест на то, что если у одного вопроса есть лучший ответ, а мы выбираем лучший ответ у другого вопроса, то у первого лучший не меняется (потому что сейчас у тебя именно так, т.е. есть баг).

2018-10-26 09:09 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
Где тесты на экшн best?

2018-10-26 09:09 UTC, vkurennov commented on spec/models/answer_spec.rb
> +  describe "Prove flip_best method" do
здесь неверные тесты. Тут должно быть 3 теста:

1. Проверяем, что при вызове метода у нужного вопроса изменился флаг best на true
2. Создаем уже лучший ответ у того же вопроса, затем у другого ответа вызываем метод, проверяем, что у предыдущего лучшего флаг был снят
3. Создаем лучший ответ у одного вопроса, а затем вызываем метод у ответа у **другого** вопроса, проверяем, что у ответа для первого вопроса флаг не изменился (тест на текущий баг)

И я рекомендую здесь попробовать применить TDD, т.е. написать сначала тесты и заодно исправить метод на инстанс-метод. Т.е. делаешь так:

1. Пишешь первый тест, вызывая метод так, как будто он уже написан.
2. Запускаешь тест, он ругается что такого метода нет
3. Пишешь **пустой** метод
4. Запускаешь тест, он падает, т.к. изменнеий не происходит
5. Пишешь в методе код **только для текущей проверки**, т.е. только устанваливаешь текущий ответ как лучший
6. Запускаешь, тест проходит
7. Пишешь второй тест, запускаешь, не проходит
8. Пишешь код в методе, чтобы прошел этот тест
9. Запускаешь, если все верно, то оба теста пройдут
10. Пишешь третий тест и т.д.

2018-10-28 14:50 UTC, aldav99 commented on app/views/answers/destroy.js.erb
> +var element = document.getElementById("<%=j @answer.id %>");
Не заметил. Визуально удаляется сам ответ и все ссылки, относящиеся к нему.

2018-11-03 11:54 UTC, vkurennov requested changes

2018-11-03 11:54 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.author_of?(@question)
Очень сложно, у тебя перемешалась бизнес-логика в контроллере и модели. Надо сделать один инстанс-метод модели, который будет делать все, что нужно (снимет флаг со старого ответа и установит у нового). Для отображения больше ничего и не нужно, в этом случае можно просто повтроно отрендерить список ответов

2018-11-03 11:54 UTC, vkurennov commented on app/models/answer.rb
> +    self.update!(best: true)
Т.к. тут несколько апдейтов, то надо применить [транзакцию](https://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html), чтобы изменения были атомарными.

2018-11-04 10:48 UTC, vkurennov approved these changes

2018-11-04 10:48 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer = Answer.find(params[:id])
Зачем здесь загружать ответ по id, если у тебя перед этим экшеном выполняется `find_answer`?

2018-11-04 10:48 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer = Answer.find(params[:id])
Можно фильтр find_answer повесить и на этот экшн

2018-11-04 10:48 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +      @question
Зачем тут эта строка?

2018-11-04 10:48 UTC, vkurennov commented on app/models/answer.rb
> +        former_best.update!(best: false)
если в теле одна строка и условие короткое, то используй постфиксную запись:

```
Answer.transaction do
  former_best.update!(best: false) if former_best
  self.update!(best: true)
end
```

2018-11-05 05:12 UTC, merged